const mongoose = require('mongoose');

const scheduleEntrySchema = new mongoose.Schema({
	employeeId: {
		type: mongoose.Schema.Types.ObjectId,
		ref: 'User',
		required: true
	},
	employeeName: {
		type: String,
		required: true
	},
	timeFrom: {
		type: String,
		required: true,
		validate: {
			validator: function(v) {
				// Validate time format HH:mm or H:mm
				return /^([0-1]?[0-9]|2[0-3]):[0-5][0-9]$/.test(v);
			},
			message: 'Time format must be HH:mm (e.g., 08:00 or 8:00)'
		}
	},
	timeTo: {
		type: String,
		required: true,
		validate: {
			validator: function(v) {
				return /^([0-1]?[0-9]|2[0-3]):[0-5][0-9]$/.test(v);
			},
			message: 'Time format must be HH:mm (e.g., 16:00 or 8:00)'
		}
	},
	createdBy: {
		type: mongoose.Schema.Types.ObjectId,
		ref: 'User',
		required: true
	},
	notes: {
		type: String,
	}
	,
	isPublished: {
		type: Boolean,
		default: true
	},
	autoGenerated: {
		type: Boolean,
		default: false
	}
}, { _id: true, timestamps: true });

const scheduleDaySchema = new mongoose.Schema({
	date: {
		type: Date,
		required: true
	},
	availabilities: [{
		employeeId: {
			type: mongoose.Schema.Types.ObjectId,
			ref: 'User',
			required: true
		},
		employeeName: {
			type: String,
			required: true
		},
		notes: {
			type: String,
			default: ''
		},
		timeWindows: [{
			timeFrom: {
				type: String,
				validate: {
					validator: function(v) {
						return !v || /^([0-1]?[0-9]|2[0-3]):[0-5][0-9]$/.test(v);
					},
					message: 'Time format must be HH:mm (e.g., 08:00)'
				}
			},
			timeTo: {
				type: String,
				validate: {
					validator: function(v) {
						return !v || /^([0-1]?[0-9]|2[0-3]):[0-5][0-9]$/.test(v);
					},
					message: 'Time format must be HH:mm (e.g., 16:00)'
				}
			}
		}],
		declaredAt: {
			type: Date,
			default: Date.now
		},
		updatedAt: {
			type: Date,
			default: Date.now
		}
	}],
	entries: [scheduleEntrySchema]
}, { _id: false });

const scheduleSchema = new mongoose.Schema({
	name: {
		type: String,
		required: true,
		trim: true
	},
	teamId: {
		type: mongoose.Schema.Types.ObjectId,
		ref: 'Team',
		required: true
	},
	type: {
		type: String,
		enum: ['team', 'department', 'custom'],
		required: true
	},
	availabilityEnabled: {
		type: Boolean,
		default: false
	},
	departmentName: {
		type: String,
		required: function() {
			return this.type === 'department';
		}
	},
	members: [{
		type: mongoose.Schema.Types.ObjectId,
		ref: 'User'
	}],
	createdBy: {
		type: mongoose.Schema.Types.ObjectId,
		ref: 'User'
	},
	days: [scheduleDaySchema],
	autoPlanConfig: {
		minEmployeesPerDay: {
			type: Number,
			default: 1,
			min: 1
		},
		defaultShiftDurationHours: {
			type: Number,
			default: 8,
			min: 1,
			max: 24
		}
	},
	isActive: {
		type: Boolean,
		default: true
	}
}, {
	collection: 'schedules',
	timestamps: true
});

// Indexes for efficient queries
scheduleSchema.index({ teamId: 1, type: 1 });
scheduleSchema.index({ teamId: 1, departmentName: 1 });
scheduleSchema.index({ teamId: 1, name: 1 });
scheduleSchema.index({ members: 1 });

module.exports = conn => (conn.models.Schedule || conn.model('Schedule', scheduleSchema));

