// utils/scheduleVisibility.js
//
// Wybieranie wpisów grafiku widocznych dla oglądającego.
//
// Kluczowa reguła: wpis nieopublikowany (isPublished === false) to SZKIC i widzi go
// wyłącznie ten, kto danym grafikiem zarządza. Moduł grafików pilnuje tego przy
// pobieraniu miesiąca (scheduleController), a ten plik pozwala trzymać się tej samej
// reguły na dashboardzie — bez powielania samych uprawnień, które przychodzą tu
// gotowe jako zbiór identyfikatorów grafików do redagowania.

const toDateKey = value => {
	const date = value instanceof Date ? value : new Date(value)
	if (Number.isNaN(date.getTime())) return null
	const month = String(date.getMonth() + 1).padStart(2, '0')
	const day = String(date.getDate()).padStart(2, '0')
	return `${date.getFullYear()}-${month}-${day}`
}

/**
 * Czy pojedynczy wpis ma trafić do oglądającego.
 * @param {Object} entry
 * @param {Object} options
 * @param {Set<String>} options.employeeIds - czyje wpisy oglądający może widzieć
 * @param {Boolean} options.canManageDrafts - czy zarządza grafikiem, z którego pochodzi wpis
 */
function isScheduleEntryVisible(entry, { employeeIds, canManageDrafts = false } = {}) {
	if (!entry) return false
	if (!employeeIds || !employeeIds.has(String(entry.employeeId))) return false
	// Szkic tylko dla zarządzającego — tak samo jak w module grafików.
	if (entry.isPublished === false && !canManageDrafts) return false
	return true
}

/**
 * Widoczne wpisy ze wszystkich grafików w zadanym zakresie dat.
 *
 * @param {Array<Object>} schedules - grafiki z polami _id, name, days[]
 * @param {Object} options
 * @param {Date} options.fromDate - początek zakresu (włącznie)
 * @param {Date} options.toDate - koniec zakresu (włącznie)
 * @param {Iterable<String>} options.employeeIds - czyje wpisy pokazujemy
 * @param {Set<String>} [options.manageableScheduleIds] - grafiki, którymi oglądający zarządza
 * @returns {Array<Object>} wpisy posortowane po dacie, a w ramach dnia po godzinie rozpoczęcia
 */
function collectVisibleScheduleEntries(
	schedules,
	{ fromDate, toDate, employeeIds, manageableScheduleIds = new Set() } = {}
) {
	if (!Array.isArray(schedules)) return []

	const allowedEmployees = employeeIds instanceof Set ? employeeIds : new Set(employeeIds || [])
	if (allowedEmployees.size === 0) return []

	const from = fromDate instanceof Date ? fromDate : new Date(fromDate)
	const to = toDate instanceof Date ? toDate : new Date(toDate)
	if (Number.isNaN(from.getTime()) || Number.isNaN(to.getTime())) return []

	const collected = []

	for (const schedule of schedules) {
		if (!schedule) continue
		const canManageDrafts = manageableScheduleIds.has(String(schedule._id))

		for (const day of schedule.days || []) {
			const dayDate = new Date(day?.date)
			if (Number.isNaN(dayDate.getTime()) || dayDate < from || dayDate > to) continue

			for (const entry of day.entries || []) {
				if (!isScheduleEntryVisible(entry, { employeeIds: allowedEmployees, canManageDrafts })) continue
				collected.push({
					id: entry._id,
					scheduleId: schedule._id,
					scheduleName: schedule.name,
					date: toDateKey(day.date),
					employeeId: String(entry.employeeId),
					employeeName: entry.employeeName,
					timeFrom: entry.timeFrom,
					timeTo: entry.timeTo,
					isPublished: entry.isPublished !== false,
					autoGenerated: entry.autoGenerated === true,
				})
			}
		}
	}

	return collected.sort((a, b) => {
		const byDate = String(a.date || '').localeCompare(String(b.date || ''))
		if (byDate !== 0) return byDate
		return String(a.timeFrom || '').localeCompare(String(b.timeFrom || ''))
	})
}

module.exports = {
	isScheduleEntryVisible,
	collectVisibleScheduleEntries,
}
